  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend-ide-deployment
    labels:
      app: frontend-ide
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: frontend-ide
    template:
      metadata:
        annotations: 
            update: bb6ddad9dd29827dde288fee12d994bb
        labels:
          app: frontend-ide
      spec:
        containers:
          - name: frontend-ide
            image: amdp-registry.skamdp.org/mydev-ywyi/frontend-ide:1.0.0
            imagePullPolicy: Always


